In [1]:
import torch

In [10]:
torch.empty(2,3) # torch basic element is a tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.rand(2,2)

tensor([[0.5177, 0.5880],
        [0.5995, 0.1041]])

In [12]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [13]:
torch.ones(2,2) # normal dtype is float

tensor([[1., 1.],
        [1., 1.]])

In [15]:
torch.ones(2,2 , dtype = torch.float16)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [18]:
x = torch.tensor([2.5,0.1])
print(x)
x.size()

tensor([2.5000, 0.1000])


torch.Size([2])

In [21]:
x = torch.rand(2,2)
y=torch.rand(2,2)

print(y.add_(x)) # _ means it will do inplace = True

z = torch.mul(x,y)
z

tensor([[1.0621, 0.7604],
        [1.1094, 0.8382]])


tensor([[0.2077, 0.3867],
        [0.8410, 0.1629]])

In [22]:
x = torch.rand(5,3)
x

tensor([[0.4021, 0.3539, 0.8084],
        [0.0581, 0.3653, 0.9575],
        [0.3709, 0.1248, 0.1264],
        [0.0438, 0.9311, 0.0941],
        [0.9829, 0.8155, 0.4615]])

In [23]:
x[:,0]

tensor([0.4021, 0.0581, 0.3709, 0.0438, 0.9829])

In [24]:
x[1,1].item()

0.3653254508972168

In [28]:
x = torch.rand(4,4)
print(x.size())
y = x.view(16) # flattens to 1d array
y

torch.Size([4, 4])


tensor([0.1274, 0.3935, 0.2878, 0.7982, 0.8251, 0.8404, 0.9678, 0.0818, 0.8694,
        0.3511, 0.5131, 0.3580, 0.6959, 0.7061, 0.1724, 0.8963])

In [33]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [34]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
x = torch.ones(5,requires_grad=True) # require_grad for gradients to be normalized
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)