In [1]:
import torch 

In [9]:
x = torch.randn(3 , requires_grad=True)
print(x)
y = x+2
print(y) # becuase of requires_grad , does back propagadtion with gradient 

z = y*y*2
z = z.mean()
print(z)

z.backward() # dz/dx # chain rule
print(x.grad)

tensor([-0.0708, -0.7184,  1.4066], requires_grad=True)
tensor([1.9292, 1.2816, 3.4066], grad_fn=<AddBackward0>)
tensor(11.3128, grad_fn=<MeanBackward0>)
tensor([2.5722, 1.7088, 4.5421])


In [13]:
# Prevent Grad History

x = torch.randn(3,requires_grad=True)
print(x)

x.requires_grad_(False)

tensor([-0.9671, -1.9039,  0.7563], requires_grad=True)


tensor([-0.9671, -1.9039,  0.7563])

In [14]:
x.detach()

tensor([-0.9671, -1.9039,  0.7563])

In [15]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.0329, 0.0961, 2.7563])


In [18]:
# Practice

weights = torch.ones(4,requires_grad=True)

for epoch in range(5):
    model_output = (weights*3).sum()
    model_output.backward() # calcs the gradient
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [21]:
weights = torch.ones(4,requires_grad=True)

optimizer = torch.optim.SGD([weights],lr=0.01) # Stohastic Graident descent SGD
optimizer.step()
optimizer.zero_grad()

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
