In [2]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)

In [4]:
x = np.array([2.0,1.0,0.1])
outputs = softmax(x) # softmax is normalzing probabilties from 0-1
print("softmax numpy:",outputs)

softmax numpy: [0.65900114 0.24243297 0.09856589]


In [5]:
x = torch.tensor([2.0,1.0,0.1])
outputs = torch.softmax(x,dim=0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [8]:
# Cross entropy
def cross_entropy(actual,predicted):
    loss = -np.sum(actual*np.log(predicted))
    return loss

# Y must be one hot encoded
# class 0 : [1 0 0]
# class 1 : [0 1 0]
# class 2 : [0 0 1]

y = np.array([1,0,0])

# y_pred has probabilities

y_pred_good = np.array([0.7,0.2,0.1])
y_pred_bad = np.array([0.1,0.3,0.6])
l1 = cross_entropy(y, y_pred_good)
l2 = cross_entropy(y, y_pred_bad)
print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')


Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


In [10]:
loss = nn.CrossEntropyLoss() # auto applies nn.LogSoftmax + nn.NLLLoss , so don't add the softmax layer , don't one-hot Y , y-hat is raw score

y = torch.tensor([0])

# nsamples*nclasses = 1*3
y_pred_good = torch.tensor([[2.0,1.0,0.1]]) # raw values
y_pred_bad = torch.tensor([[0.5,2.0,0.3]]) 

l1 = loss(y_pred_good,y)
l2 = loss(y_pred_bad,y)

print(f"Loss 1 Good Predictions {l1.item()}")
print(f"Loss 2 Bad Predictions {l2.item()}")


Loss 1 Good Predictions 0.4170299470424652
Loss 2 Bad Predictions 1.840616226196289


In [12]:
_,predcitions1 = torch.max(y_pred_good,1)
_,predcitions2 = torch.max(y_pred_bad,1)
print(predcitions1) # prediction class
print(predcitions2) # prediction class

tensor([0])
tensor([1])


In [15]:
# increase samples

# 3 samples

y = torch.tensor([2,0,1]) # True Y values

#nsamples * nclass = 3x3

y_pred_good = torch.tensor([ [0.1,1.0,2.1],[2.0,1.0,0.1],[0.1,3.0,0.1] ]) # raw values
y_pred_bad = torch.tensor([ [2.1,1.0,0.1], [0.1,1.0,2.1] , [0.1,3.0,0.1] ])

l1 = loss(y_pred_good , y)
l2 = loss(y_pred_bad, y )

print(f"Loss 1 Good Predictions {l1.item()}")
print(f"Loss 2 Bad Predictions {l2.item()}")

_,predcitions1 = torch.max(y_pred_good,1)
_,predcitions2 = torch.max(y_pred_bad,1)
print(predcitions1) # prediction class
print(predcitions2) # prediction class

Loss 1 Good Predictions 0.3018244206905365
Loss 2 Bad Predictions 1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])


In [16]:
# Neural Net with Softmax Mutiple Classes

class NeuralNet2(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNet2,self).__init__()
        self.linear1 = nn.Linear(input_size,hidden_size) # Input Layer
        self.relu = nn.ReLU() # activation function layer
        self.linear2 = nn.Linear(hidden_size,num_classes) # output Layer
        
    def forward(self,x):
        # Applies layers
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # no softmax because we use nn.CrossEntropyLoss()
        return out

model = NeuralNet2(input_size=28*28,hidden_size=5,num_classes=3)
criterion = nn.CrossEntropyLoss() # applies softmax auto

In [18]:
# Neural Net with Sigmoid Binary Classifcation

class NeuralNet1(nn.Module):
    def __init__(self,input_size,hidden_size):
        super(NeuralNet1,self).__init__()
        self.linear1 = nn.Linear(input_size,hidden_size) # Input Layer
        self.relu = nn.ReLU() # activation function layer
        self.linear2 = nn.Linear(hidden_size,1) # output Layer # 1 becuase its a binary classifcation
        
    def forward(self,x):
        # Applies layers
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # no softmax because we use nn.CrossEntropyLoss()
        y_pred = torch.sigmoid(out)
        return y_pred

model = NeuralNet1(input_size=28*28,hidden_size=5)
criterion = nn.BCELoss() # binaryCrossenTropy